server:
  port: 8889

spring:
  datasource:
    url: jdbc:mysql://39.108.55.93:3306/person?useUnicode=true&characterEncoding=utf-8&useOldAliasMetadataBehavior=true
    password: 123456
    username: person
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver



  jpa:
    show-sql: true

  servlet:
    multipart:
      max-file-size: 10MB
  redis:
    database: 2

mybatis:
  type-aliases-package: cn.gson.linyun.model.pojos
  mapper-locations: classpath:mappers/*/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    call-setters-on-nulls: true
    map-underscore-to-camel-case: true
    cache-enabled: true

